### ISSUE TITLE
BDK config does not allow to configure keyAuth

### ISSUE THREAD

**Issue by symphony-thibault** [finos/symphony-bdk-java#694]
## Bug Report

Hi team, 

The BDK config does not allow configuring a specific host and port for the [Key Manager certificate authentication](https://developers.symphony.com/restapi/reference/key-manager-authenticate). 

For instance, I'd expect something like: 
```yaml
host: localhost.symphony.com
port: 8443

sessionAuth:
  host: keymanager.symphony.com
  port: 8444

keyManager:
  host: localhost.symphony.com
  port: 9443

# here is what could be missing
keyAuth:
  host: localhost.symphony.com
  port: 9444

bot:
  username: tibot
  certificate:
    path: /Users/thibault.pensec/local/sec/cert-auth-demo/tibot.p12
    password: changeit
```

Thanks for your advice!
